### ISSUE TITLE
Wrong method used in Array Test

### ISSUE THREAD

**Issue by john9hoff** [alarinel/challenges#2]
https://github.com/alarinel/challenges/blob/723c8487722fc95a5de6913fcf1b5d55d459fda9/SimpleChallenges/src/main/test/ArrayTest.java#L20

Should be calculateMultiplicationOfElements instead of calculateAverageOfElements.

**Comment by alarinel** [comment]
Thanks John! I don't think we ever actually made it that far into the testing, lol!
